Added support for detecting and specifying ports.
jneilliii/OctoPrint-WemoSwitch pull request #39
Opened 2021-01-03 19:19 UTC by dstrohl

Added the ability to support entering an IP address:port number string instead of just a address.  I am using a device (https://dlidirect.com/products/new-pro-switch) that can simulate a wemo plug, however it uses different ports for each of the plugs on the power-strip.  

if no port number is found in the address string, it will simply use your existing code.

I also added a dump into the log in the startup script to detail the information it found in the discover devices (which can help people find their device.)

There is also a method now that will return that device discovery information in a format that should be useful for adding a combo-box/dropdown list to the ui with the found devices (I don't know the OctoPrint UI approach to know how to add it, or I would have added that as well, it should be a combo-box though so people can still add in addresses that were not discovered.)  None of this though should impact anything if you don't want to add this, it's there if desired, but should not impact anything.

2021-01-03 19:30 UTC, dstrohl commented
Note I don't have an octoprint test environment so I haven't tested this yet.

2021-01-03 20:07 UTC, jneilliii commented
Thanks @dstrohl I will test/verify this against my standard wemo, thanks for the contribution.

2021-01-03 20:08 UTC, jneilliii commented
people have much wanted the discovery option to function, so I will look into adding the UI for that as well, again thanks for the contribution.

2021-01-06 20:06 UTC, jneilliii requested changes
I'll have to look into the documentation and see what this method wants relative to the index value, unless you already know. Is it just a matter of making it like this?

```
d = self.get_discovered_device(index, as_text=as_choice or as_text)
```

2021-01-06 20:06 UTC, jneilliii commented on octoprint_wemoswitch/__init__.py
> +			d = self.get_discovered_device(as_text=as_choice or as_text)
When testing your implementation I get the following error in octoprint.log.

```
2021-01-06 14:59:23,836 - octoprint.plugin - ERROR - Error while calling plugin wemoswitch
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_wemoswitch/__init__.py", line 117, in on_after_startup
    for d in self.get_discovered_devices():
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_wemoswitch/__init__.py", line 173, in get_discovered_devices
    d = self.get_discovered_device(as_text=as_choice or as_text)
TypeError: get_discovered_device() missing 1 required positional argument: 'index'
```

2021-01-06 21:49 UTC, jneilliii approved these changes

2021-01-06 21:51 UTC, jneilliii commented
That indeed seem to resolve the issue, but I need to dig into it a little more before merging, but it is now logging the device as intended on startup now. Thanks again for this PR.

```
[2021-01-06 16:04:49,662] DEBUG: Device 0: [(0, [...])]
```

2021-01-06 22:15 UTC, jneilliii commented
I've merged in your changes local and pushed back up to my rc branch. I will be putting together the UI bits this weekend I think.

2021-01-06 22:15 UTC, closed without merging